---
title: "Lab 4"
author: "Sharleen Price spp2122"
date: "February 9, 2018"
output: pdf_document
---

# Instructions 
Before the lab is due, make sure that you upload an RMarkdown file to the canvas page (this should have a .Rmd extension) as well as the PDF or HTML output after you have knitted the file (this will have a .pdf or .html extension).  Note that since you have already knitted this file, you should see both a **Lab4_UNI.pdf** and a **Lab4_UNI.Rmd** file in your UN2102 folder.  Click on the **Files** tab to the right to see this.  The files you upload to the Canvas page should be updated with commands you provide to answer each of the questions below.  You can edit this file directly to produce your final solutions.  

# Background: Edgar Anderson's Iris Data

The R data description follows:

This famous (Fisher's or Anderson's) iris data set gives the measurements in centimeters of the variables sepal length and width and petal length and width, respectively, for 50 flowers from each of 3 species of iris. The species are Iris setosa, versicolor, and virginica.



# Task 

The purpose of this lab is to construct a complex plot using base **R** graphics.  Construct the exact plot **Gabrielplot.png** that is posted on Canvas.  Move the legend to the **topleft**, change the **xlab** \& **ylab** to **Sepal Length** \& **Petal Length** respectively, and change the title to something esle.   

```{r}
## R code goes here 
cols = c("black", "red", "green")
plot(iris$Sepal.Length, iris$Petal.Length, xlab="Sepal Length", ylab="Petal Length",col = cols[iris$Species] , main="Sharleen's Plot")

legend("topleft", legend = levels(iris$Species), col = c("black", "red", "green"), fill=1:length(levels(iris$Species)))

species <- levels(iris$Species)
counter<-1
for (i in species)
{
  color<-cols[counter]
  this_species <- iris$Species == i
  species_data <-iris[this_species,]
  lines<- lm(species_data$Petal.Length~species_data$Sepal.Length)
  abline(lines, col = color)
  counter <- counter + 1
}
points(4.9, 4.5,  pch = "*", col = "green")
points(5.1, 3,  pch = "*", col = "red")
points(5.8, 1.2,  pch = "*", col = "black")

text(4.9,4.9,"(4.9,4.5)",col="green")
text(5.4,3,"(5.1,3)",col="red")
text(6.1,1.2,"(5.8,1.2)",col="black")
?abline
#lm(y~x)
```


